name: Build and publish Docker images

on:
    push:
        branches:
            - main

env:
    platforms: "linux/amd64,linux/arm64"
    registry_path: "ghcr.io/benediktbertsch/playwright-bun-image"

jobs:
    publish-docker:
        runs-on: ubuntu-latest
        permissions:
            packages: write
            contents: read
            attestations: write
            id-token: write
        strategy:
            fail-fast: false
        steps:
        - name: Check out repository
          uses: actions/checkout@v4
        - name: Set up QEMU to build multiplatform docker images
          uses: docker/setup-qemu-action@v3.6.0
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3.10.0
          with:
              version: latest
        - name: Login into registry
          uses: docker/login-action@v3.4.0
          with:
              registry: ghcr.io
              username: ${{github.actor}}
              password: ${{secrets.GITHUB_TOKEN}}
        - name: Calculate metadata
          uses: docker/metadata-action@v5.7.0
          id: meta
          with:
            images: ${{ env.registry_path }}
            tags: |
                type=schedule
                type=ref,event=branch
                type=ref,event=pr
                type=semver,pattern={{version}}
                type=semver,pattern={{major}}.{{minor}}
                type=semver,pattern={{major}}
                type=sha
          env:
            DOCKER_METADATA_ANNOTATIONS_LEVELS: index
        - name: Build and deploy docker images
          uses: docker/build-push-action@v6.15.0
          id: build
          with:
              push: true
              file: Dockerfile
              build-args: |
              platforms: ${{ env.platforms }}
              tags: ${{ steps.meta.outputs.tags }}
              labels: ${{ steps.meta.outputs.labels }}
              provenance: "mode=max"
        - name: Install Cosign
          uses: sigstore/cosign-installer@v3.8.1
        - name: Sign the docker images
          run: |
            cosign sign --recursive --yes "${{ env.registry_path }}@${{ steps.build.outputs.digest }}"
